#!/bin/bash

SNAP_CHANNEL=--candidate

echo "Enabling wasmedge via crun OCI runtime"

echo "Install/Upgrade crun-wasmedge from snapstore"
[ ! -d "/snap/crun-wasmedge/current" ] && sudo snap install $SNAP_CHANNEL crun-wasmedge || sudo snap refresh $SNAP_CHANNEL crun-wasmedge
sudo ln -sf /snap/crun-wasmedge/current/crun.wrapper /usr/local/bin/crun

echo "Switching OCI runtime to crun with wasmedge support"
sed 's/default_runtime_name = \"\${RUNTIME}\"/default_runtime_name = \"crun\"/g' $SNAP/microk8s-resources/default-args/containerd-template.toml > $SNAP_DATA/args/containerd-template.toml
sudo systemctl restart snap.microk8s.daemon-containerd

sudo touch $SNAP_DATA/var/lock/kata.enabled
echo "Enabled wasmedge via crun OCI runtime"
